export { useSearchPosts } from './model/useSearchPosts'
export { useAddPosts } from './model/useAddPosts'
export { useFetchPosts } from './model/useFetchPosts'
export { useDeletePosts } from './model/useDeletePosts'
export { useUpdatePosts } from './model/useUpdatePosts'
